TCPIP_ERROR_CODES = {
    "0": "Operation successful",
    "550": "Unknown error",
    "551": "Operation blocked",
    "552": "Invalid parameters",
    "553": "Memory not enough",
    "554": "Create socket failed",
    "555": "Operation not supported",
    "556": "Socket bind failed",
    "557": "Socket listen failed",
    "558": "Socket write failed",
    "559": "Socket read failed",
    "560": "Socket accept failed",
    "561": "Open PDP context failed",
    "562": "Close PDP context failed",
    "563": "Socket identity has been used",
    "564": "DNS busy",
    "565": "DNS parse failed",
    "566": "Socket connect failed",
    "567": "Socket has been closed",
    "568": "Operation busy",
    "569": "Operation timeout",
    "570": "PDP context broken down",
    "571": "Cancel send",
    "572": "Operation not allowed",
    "573": "APN not configured",
    "574": "Port busy",
    "-1": "Unable to match response"
}
